# set ft=markdown for okish TS syntax highlighting
index : package_nuvoton_index.json

core-version  : 0.4.9
tools-version : 1.0.0
release-url   : https://github.com/is-tg/n76e003-core/releases/download

core-archive           : n76e003-core.tar.gz
linux-tools-archive    : linux-bundle.tar.gz
windows-tools-archive  : windows-bundle.tar.gz

# core
core-download-url : `release-url`/v`core-version`/`core-archive`
core-sha256       : sha256 ar/`core-archive`
core-checksum     : SHA-256:`core-sha256`
core-archive-size : bytes ar/`core-archive`

index.packages.0.platforms.0.version  : `core-version`
index.packages.0.platforms.0.url      : `core-download-url`
index.packages.0.platforms.0.checksum : `core-checksum`
index.packages.0.platforms.0.size     : `core-archive-size`

index.packages.0.platforms.0.toolsDependencies.0.version : `tools-version`
index.packages.0.tools.0.version                         : `tools-version`

# linux
linux-tools-url      : `release-url`/v`core-version`/`linux-tools-archive`
linux-tools-sha256   : sha256 ar/`linux-tools-archive`
linux-tools-checksum : SHA-256:`linux-tools-sha256`
linux-tools-size     : bytes ar/`linux-tools-archive`

index.packages.0.tools.0.systems.0.url      : `linux-tools-url`
index.packages.0.tools.0.systems.0.checksum : `linux-tools-checksum`
index.packages.0.tools.0.systems.0.size     : `linux-tools-size`

# windows
windows-tools-url      : `release-url`/v`core-version`/`windows-tools-archive`
windows-tools-sha256   : sha256 ar/`windows-tools-archive`
windows-tools-checksum : SHA-256:`windows-tools-sha256`
windows-tools-size     : bytes ar/`windows-tools-archive`

index.packages.0.tools.0.systems.1.url      : `windows-tools-url`
index.packages.0.tools.0.systems.1.checksum : `windows-tools-checksum`
index.packages.0.tools.0.systems.1.size     : `windows-tools-size`
