name: Compile Examples

on:
  workflow_dispatch:

jobs:
  compile:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y sdcc

      - name: Compile sketches
        uses: arduino/compile-sketches@v1
        with:
          fqbn: istg:mcs51:n76e003
          platforms: |
            - name: istg:mcs51
              source-url: https://raw.githubusercontent.com/is-tg/n76e003-core/main/package_istg_index.json
          sketch-paths: |
            - examples
