name: Compile Examples

on: [push, pull_request]

jobs:
  compile:
    strategy:
      matrix:
        os: [ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v4

      - name: Download Toolchain Bundle
        run: |
          wget https://github.com/is-tg/n76e003-core/releases/latest/download/toolchain-bundle.tar.gz -O toolchain.tar.gz
          mkdir -p /opt/toolchain-bundle
          tar -xzf toolchain.tar.gz -C /opt/toolchain-bundle --strip-components=1

      - uses: arduino/compile-sketches@v1
        with:
          fqbn: nuvoton:mcs51:n76e003
          cli-compile-flags: |
            - --build-property
            - runtime.tools.bundle.path=/opt/toolchain-bundle
          platforms: |
            - source-path: ./
              name: nuvoton:mcs51
          sketch-paths: |
            - examples
